apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-gerenciamento-service
spec:
  # type: NodePort
  selector:
    app: tech-challenge-api-gerenciamento
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    # nodePort: 30007
    targetPort: 80
    # targetPort: 3000
  type: ClusterIP